### ISSUE TITLE
configure: error: Package requirements (bluez >= 5.0) were not met:

### ISSUE THREAD

**Issue by stefanofornari** [raspberrypi-ui/bluealsa#6]
Hello,
I am trying to build on a raspberry PI 2B and I get 

configure: error: Package requirements (bluez >= 5.0) were not met:

BlueZ is indeed installed:

sudo apt-get install bluez
Reading package lists... Done
Building dependency tree       
Reading state information... Done
bluez is already the newest version (5.50-1.2~deb10u1+rpt1).

**Comment by stefanofornari** [comment]
Googling, I found an hint and installed the following dependencies:

sudo apt-get install libbluetooth-dev
sudo apt-get install libdbus-glib-1-dev

which fixed the issue

**Comment by spl237** [comment]
For future reference, "sudo apt build-dep <package-name>" automaticall installs all a package's build dependencies, and would have installed those two for you here.

**Comment by stefanofornari** [comment]
actually many more deps are missing.... I am trying to collect them.

now it sayss fdk-aac is missing. which package should I install?

> sudo apt build-dep bluealsa

Reading package lists... Done
E: You must put some 'source' URIs in your sources.list
:(

**Comment by stefanofornari** [comment]
I found in another ticket the solution for fdt-aac.
here the dependencies I needed to install:

sudo apt-get install libbluetooth-dev
sudo apt-get install libdbus-glib-1-dev
sudo apt-get install libsbc-dev

**Comment by spl237** [comment]
I have just checked on a clean Raspbian image:

sudo apt build-dep bluealsa
sudo apt source bluealsa
cd bluealsa-xx
dpkg-buildpackage -sa

This builds a correct Debian package without errors.

You do not seem to understand the basics of building code from Debian source, correctly configuring apt etc - please open a thread on the forums and ask for help there, rather than raising issues here. This is purely intended for reporting actual bugs in the code.
